### ISSUE TITLE
AMPL question

### ISSUE THREAD

**Issue by syarra** [optimizers/nlpy#21]
When evaluating Hessian in AMPL, I noticed that it returns a full sparse matrix, even though it is a symmetric matrix. 
Is there a way to only have the lower triangular part by setting an option?

If not, I will do it in cython.

**Comment by dpo** [comment]
Does it really do that? I don't see code that fills out the lower triangle:
https://github.com/dpo/nlpy/blob/develop/nlpy/model/src/_amplpy.pyx#L586

``` python
In [1]: from nlpy.model import AmplModel

In [2]: nlp = AmplModel("rosenbrock.nl")

In [3]: nlp.obj(nlp.x0)
Out[3]: 32.308641975308646

In [4]: nlp.grad(nlp.x0)
Out[4]: array([ -75.40740741,  111.11111111])

In [5]: nlp.hess(nlp.x0)
Out[5]:
(array([-131.33333333, -133.33333333,  200.        ]),
 array([0, 0, 1]),
 array([0, 1, 1]))
```

**Comment by syarra** [comment]
Oh, I see! I got confused by the doctring ...
in `amplpy.py` it is stated Lower triangular, but in `src/_amplpy.pyx` it is Upper triangular.

AMPL is then returning the upper triangular matrix only ...

**Comment by dpo** [comment]
Yes, AMPL returns the upper triangle. Let's fix the inconsistency.
